# -*- coding: utf-8 -*-
"""MMRAG1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TB03iMbprmtH7lTchyTV3CmEhEUzfu0d
"""



import torch
import pandas as pd
import numpy as np
import faiss
from transformers import AutoTokenizer, AutoModel, pipeline
from transformers import CLIPProcessor, CLIPModel

# Load models
ehr_model = AutoModel.from_pretrained("bert-base-uncased")
ehr_tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
clip_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

ehr_data = pd.DataFrame({
    "Patient_ID": [101, 102, 103],
    "Diagnosis": ["Type 2 Diabetes", "Hypertension", "Asthma"],
    "Medications": ["Metformin", "Lisinopril", "Albuterol"]
})

physician_notes = [
    "Patient has high HbA1c. Recommend metformin.",
    "Elevated BP readings. Monitor and start Lisinopril.",
    "Wheezing and breathlessness. Administer albuterol inhaler."
]

def encode_ehr_text(text):
    inputs = ehr_tokenizer(text, return_tensors="pt", padding=True, truncation=True)
    with torch.no_grad():
        outputs = ehr_model(**inputs)
    return outputs.last_hidden_state[:, 0, :].squeeze().numpy()

ehr_embeddings = np.vstack([
    encode_ehr_text(f"{row.Diagnosis}, {row.Medications}") for _, row in ehr_data.iterrows()
])

def encode_clip_text(text):
    inputs = clip_processor(text=[text], return_tensors="pt", padding=True)
    with torch.no_grad():
        outputs = clip_model.get_text_features(**inputs)
    return outputs.squeeze().numpy()

note_embeddings = np.vstack([
    encode_clip_text(note) for note in physician_notes
])

ehr_embeddings = np.vstack([
    encode_ehr_text(f"{row.Diagnosis}, {row.Medications}") for _, row in ehr_data.iterrows()
])

note_embeddings = np.vstack([
    encode_clip_text(note) for note in physician_notes
])

ehr_index = faiss.IndexFlatL2(ehr_embeddings.shape[1])
note_index = faiss.IndexFlatL2(note_embeddings.shape[1])

ehr_index.add(ehr_embeddings)
note_index.add(note_embeddings)

# ✅ Step 8: Define Multimodal Search
def multimodal_search(query):
    query_clip = encode_clip_text(query)
    query_bert = encode_ehr_text(query)

    _, I_notes = note_index.search(np.expand_dims(query_clip, axis=0), k=1)
    _, I_ehrs = ehr_index.search(np.expand_dims(query_bert, axis=0), k=1)

    ehr_result = ehr_data.iloc[I_ehrs[0][0]].to_dict()
    note_result = physician_notes[I_notes[0][0]]

    return ehr_result, note_result

# ✅ Step 9: Load Generator Model
generator = pipeline("text-generation", model="gpt2")

# ✅ Step 10: Generate Clinical Documentation
def generate_clinical_documentation(query):
    ehr_result, note_result = multimodal_search(query)

    prompt = f"""
You are a clinical assistant. Based on the following:

EHR:
Diagnosis: {ehr_result['Diagnosis']}
Medications: {ehr_result['Medications']}

Physician Notes:
{note_result}

Generate a structured medical summary.
"""

    output = generator(prompt, max_length=200, num_return_sequences=1)
    return output[0]['generated_text']

query = "Patient has high blood sugar and fatigue"
print(generate_clinical_documentation(query))


import evaluate

# Load ROUGE and BLEU metrics from the 'evaluate' library
rouge_metric = evaluate.load("rouge")
bleu_metric = evaluate.load("bleu")

# Function to evaluate BLEU and ROUGE scores
def evaluate_generated_summary(reference_summary, generated_summary):
    # Compute BLEU score
    bleu_score = bleu_metric.compute(predictions=[generated_summary], references=[[reference_summary]])

    # Compute ROUGE score
    rouge_score = rouge_metric.compute(predictions=[generated_summary], references=[reference_summary])

    return bleu_score, rouge_score

# Example generated and reference summary
reference_summary = "The patient has diabetes and is prescribed Metformin."
generated_summary = generate_clinical_documentation("Document a case for a diabetic patient.")

# Evaluate the generated summary
bleu_score, rouge_score = evaluate_generated_summary(reference_summary, generated_summary)

# Print out the BLEU and ROUGE scores
print(f"BLEU Score: {bleu_score}")
print(f"ROUGE Score: {rouge_score}")



print(rouge_score)

print(bleu_score)  # This will show the structure of the BLEU score

bleu_score_value = bleu_score['bleu']  # This will retrieve the BLEU score value

rouge_score_value = rouge_score['rougeL']

import matplotlib.pyplot as plt

# Assuming you already have the BLEU and ROUGE scores
bleu_score_value = bleu_score["bleu"]  # BLEU score is stored under 'bleu' key

# Access ROUGE-L score directly
rouge_score_value = rouge_score['rougeL']  # Access the value of 'rougeL'

# Labels for the scores
metrics = ['BLEU', 'ROUGE-L']

# Values of the scores
scores = [bleu_score_value, rouge_score_value]

# Plotting the bar graph
plt.figure(figsize=(8, 5))
plt.bar(metrics, scores, color=['blue', 'green'])

# Adding labels and title
plt.xlabel('Metrics')
plt.ylabel('Scores')
plt.title('Evaluation of Generated Clinical Documentation')

# Show the plot
plt.show()

